import React from "react";
import { Form } from "react-formio";

const RenderForm = (props) => {
  return (
    <Form
      form={{
        display: "form",
        components: [
          {
            label: "Account Type",
            labelPosition: "top",
            widget: "choicesjs",
            placeholder: "Please Select",
            description: "",
            tooltip: "",
            customClass: "",
            tabindex: "",
            hidden: false,
            hideLabel: false,
            uniqueOptions: false,
            autofocus: false,
            disabled: false,
            tableView: true,
            modalEdit: false,
            multiple: false,
            dataSrc: "values",
            data: {
              values: [
                {
                  label: "Checking Account",
                  value: "checkingAccount",
                },
                {
                  label: "Saving Account",
                  value: "savingAccount",
                },
                {
                  label: "IRA Account",
                  value: "iraAccount",
                },
                {
                  label: "A Money Market Account",
                  value: "aMoneyMarketAccount",
                },
              ],
              resource: "",
              url: "",
              json: "",
              custom: "",
            },
            dataType: "",
            idPath: "id",
            valueProperty: "",
            template: "<span>{{ item.label }}</span>",
            refreshOn: "",
            refreshOnBlur: "",
            clearOnRefresh: false,
            searchEnabled: true,
            selectThreshold: 0.3,
            readOnlyValue: false,
            customOptions: {},
            useExactSearch: false,
            persistent: true,
            protected: false,
            dbIndex: false,
            encrypted: false,
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validateOn: "change",
            validate: {
              required: false,
              onlyAvailableItems: false,
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            unique: false,
            errorLabel: "",
            errors: "",
            key: "accountType",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "select",
            indexeddb: {
              filter: {},
            },
            selectFields: "",
            searchField: "",
            searchDebounce: 0.3,
            minSearch: 0,
            filter: "",
            limit: 100,
            redrawOn: "",
            input: true,
            prefix: "",
            suffix: "",
            dataGridLabel: false,
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            authenticate: false,
            ignoreCache: false,
            lazyLoad: true,
            fuseOptions: {
              include: "score",
              threshold: 0.3,
            },
            id: "ex6hbhj",
            defaultValue: "Checking Account",
          },
          {
            label: "Currency Type",
            labelPosition: "top",
            widget: "choicesjs",
            placeholder: "Please Select",
            description: "",
            tooltip: "",
            customClass: "",
            tabindex: "",
            hidden: false,
            hideLabel: false,
            uniqueOptions: false,
            autofocus: false,
            disabled: false,
            tableView: true,
            modalEdit: false,
            multiple: false,
            dataSrc: "values",
            data: {
              values: [
                {
                  label: "USD - US Dollar",
                  value: "usdUsDollar",
                },
                {
                  label: "EUR - Euro",
                  value: "eurEuro",
                },
                {
                  label: "GBP - Pound Sterling",
                  value: "gbpPoundSterling",
                },
              ],
              resource: "",
              url: "",
              json: "",
              custom: "",
            },
            dataType: "",
            idPath: "id",
            valueProperty: "",
            template: "<span>{{ item.label }}</span>",
            refreshOn: "",
            refreshOnBlur: "",
            clearOnRefresh: false,
            searchEnabled: true,
            selectThreshold: 0.3,
            readOnlyValue: false,
            customOptions: {},
            useExactSearch: false,
            persistent: true,
            protected: false,
            dbIndex: false,
            encrypted: false,
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validateOn: "change",
            validate: {
              required: false,
              onlyAvailableItems: false,
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            unique: false,
            errorLabel: "",
            errors: "",
            key: "currencyType",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "select",
            indexeddb: {
              filter: {},
            },
            selectFields: "",
            searchField: "",
            searchDebounce: 0.3,
            minSearch: 0,
            filter: "",
            limit: 100,
            redrawOn: "",
            input: true,
            prefix: "",
            suffix: "",
            dataGridLabel: false,
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            authenticate: false,
            ignoreCache: false,
            lazyLoad: true,
            fuseOptions: {
              include: "score",
              threshold: 0.3,
            },
            id: "ewhwpso",
            defaultValue: "USD - US Dollar",
          },
          {
            label: "Name",
            labelPosition: "top",
            disabled: true,
            placeholder: "Enter Your Full Name",
            description: "",
            tooltip: "",
            prefix: "",
            suffix: "",
            widget: {
              type: "input",
            },
            inputMask: "",
            displayMask: "",
            allowMultipleMasks: false,
            customClass: "",
            tabindex: "",
            autocomplete: "",
            hidden: false,
            hideLabel: false,
            showWordCount: false,
            showCharCount: false,
            mask: false,
            autofocus: false,
            spellcheck: true,
            disabled: false,
            tableView: true,
            modalEdit: false,
            multiple: false,
            persistent: true,
            inputFormat: "plain",
            protected: false,
            dbIndex: false,
            case: "",
            truncateMultipleSpaces: false,
            encrypted: false,
            redrawOn: "",
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validateOn: "change",
            validate: {
              required: false,
              pattern: "",
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              minLength: "",
              maxLength: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            unique: false,
            errorLabel: "",
            errors: "",
            key: "name",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "textfield",
            input: true,
            refreshOn: "",
            dataGridLabel: false,
            addons: [],
            inputType: "text",
            id: "eps4u2j",
            defaultValue: props.value,
          },
          {
            label: "Phone Number",
            labelPosition: "top",
            placeholder: "",
            description: "",
            tooltip: "",
            prefix: "",
            suffix: "",
            widget: {
              type: "input",
            },
            inputMask: "(999) 999-9999",
            displayMask: "",
            allowMultipleMasks: false,
            customClass: "",
            tabindex: "",
            autocomplete: "",
            hidden: false,
            hideLabel: false,
            mask: false,
            autofocus: false,
            spellcheck: true,
            disabled: false,
            tableView: true,
            modalEdit: false,
            multiple: false,
            persistent: true,
            inputFormat: "plain",
            protected: false,
            dbIndex: false,
            case: "",
            truncateMultipleSpaces: false,
            encrypted: false,
            redrawOn: "",
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validateOn: "change",
            validate: {
              required: false,
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
              minLength: "",
              maxLength: "",
              pattern: "",
            },
            unique: false,
            errorLabel: "",
            errors: "",
            key: "phoneNumber",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "phoneNumber",
            input: true,
            refreshOn: "",
            dataGridLabel: false,
            showCharCount: false,
            showWordCount: false,
            addons: [],
            inputType: "tel",
            inputMode: "decimal",
            id: "emiq72",
            defaultValue: "(999) 999-9999",
          },
          {
            label: "Email",
            labelPosition: "top",
            placeholder: "",
            description: "",
            tooltip: "",
            prefix: "",
            suffix: "",
            widget: {
              type: "input",
            },
            displayMask: "",
            customClass: "",
            tabindex: "",
            autocomplete: "",
            hidden: false,
            hideLabel: false,
            mask: false,
            autofocus: false,
            spellcheck: true,
            disabled: false,
            tableView: true,
            modalEdit: false,
            multiple: false,
            persistent: true,
            inputFormat: "plain",
            protected: false,
            dbIndex: false,
            case: "",
            truncateMultipleSpaces: false,
            encrypted: false,
            redrawOn: "",
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validateOn: "change",
            validate: {
              required: false,
              pattern: "",
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              minLength: "",
              maxLength: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            unique: false,
            kickbox: {
              enabled: false,
            },
            errorLabel: "",
            errors: "",
            key: "email",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "email",
            input: true,
            refreshOn: "",
            dataGridLabel: false,
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            inputType: "email",
            inputMask: "",
            id: "estjcna",
            defaultValue: "sonali121.k@gmail.com",
          },
          {
            label: "Address",
            labelPosition: "top",
            enableManualMode: false,
            disableClearIcon: false,
            placeholder: "",
            description: "",
            tooltip: "",
            customClass: "",
            tabindex: "",
            hidden: false,
            hideLabel: false,
            autofocus: false,
            disabled: false,
            tableView: false,
            modalEdit: false,
            multiple: false,
            persistent: true,
            protected: false,
            dbIndex: false,
            encrypted: false,
            redrawOn: "",
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            provider: "google",
            manualModeViewString: "",
            validate: {
              required: false,
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            unique: false,
            validateOn: "change",
            errorLabel: "",
            errors: "",
            key: "address",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "address",
            providerOptions: {
              params: {
                autocompleteOptions: {},
                key: "AIzaSyBNL2e4MnmyPj9zN7SVAe428nCSLP1X144",
              },
            },
            switchToManualModeLabel:
              "Can't find address? Switch to manual mode.",
            input: true,
            prefix: "",
            suffix: "",
            refreshOn: "",
            dataGridLabel: false,
            widget: null,
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            tree: true,
            lazyLoad: false,
            components: [
              {
                label: "Address 1",
                tableView: false,
                key: "address1",
                type: "textfield",
                input: true,
                customConditional:
                  "show = _.get(instance, 'parent.manualMode', false);",
                placeholder: "",
                prefix: "",
                customClass: "",
                suffix: "",
                multiple: false,
                defaultValue: null,
                protected: false,
                unique: false,
                persistent: true,
                hidden: false,
                clearOnHide: true,
                refreshOn: "",
                redrawOn: "",
                modalEdit: false,
                dataGridLabel: false,
                labelPosition: "top",
                description: "",
                errorLabel: "",
                tooltip: "",
                hideLabel: false,
                tabindex: "",
                disabled: false,
                autofocus: false,
                dbIndex: false,
                customDefaultValue: "",
                calculateValue: "",
                calculateServer: false,
                widget: {
                  type: "input",
                },
                attributes: {},
                validateOn: "change",
                validate: {
                  required: false,
                  custom: "",
                  customPrivate: false,
                  strictDateValidation: false,
                  multiple: false,
                  unique: false,
                  minLength: "",
                  maxLength: "",
                  pattern: "",
                },
                conditional: {
                  show: null,
                  when: null,
                  eq: "",
                },
                overlay: {
                  style: "",
                  left: "",
                  top: "",
                  width: "",
                  height: "",
                },
                allowCalculateOverride: false,
                encrypted: false,
                showCharCount: false,
                showWordCount: false,
                properties: {},
                allowMultipleMasks: false,
                addons: [],
                mask: false,
                inputType: "text",
                inputFormat: "plain",
                inputMask: "",
                displayMask: "",
                spellcheck: true,
                truncateMultipleSpaces: false,
                id: "efy8olm",
              },
              {
                label: "Address 2",
                tableView: false,
                key: "address2",
                type: "textfield",
                input: true,
                customConditional:
                  "show = _.get(instance, 'parent.manualMode', false);",
                placeholder: "",
                prefix: "",
                customClass: "",
                suffix: "",
                multiple: false,
                defaultValue: null,
                protected: false,
                unique: false,
                persistent: true,
                hidden: false,
                clearOnHide: true,
                refreshOn: "",
                redrawOn: "",
                modalEdit: false,
                dataGridLabel: false,
                labelPosition: "top",
                description: "",
                errorLabel: "",
                tooltip: "",
                hideLabel: false,
                tabindex: "",
                disabled: false,
                autofocus: false,
                dbIndex: false,
                customDefaultValue: "",
                calculateValue: "",
                calculateServer: false,
                widget: {
                  type: "input",
                },
                attributes: {},
                validateOn: "change",
                validate: {
                  required: false,
                  custom: "",
                  customPrivate: false,
                  strictDateValidation: false,
                  multiple: false,
                  unique: false,
                  minLength: "",
                  maxLength: "",
                  pattern: "",
                },
                conditional: {
                  show: null,
                  when: null,
                  eq: "",
                },
                overlay: {
                  style: "",
                  left: "",
                  top: "",
                  width: "",
                  height: "",
                },
                allowCalculateOverride: false,
                encrypted: false,
                showCharCount: false,
                showWordCount: false,
                properties: {},
                allowMultipleMasks: false,
                addons: [],
                mask: false,
                inputType: "text",
                inputFormat: "plain",
                inputMask: "",
                displayMask: "",
                spellcheck: true,
                truncateMultipleSpaces: false,
                id: "ezqb5bm",
              },
              {
                label: "City",
                tableView: false,
                key: "city",
                type: "textfield",
                input: true,
                customConditional:
                  "show = _.get(instance, 'parent.manualMode', false);",
                placeholder: "",
                prefix: "",
                customClass: "",
                suffix: "",
                multiple: false,
                defaultValue: null,
                protected: false,
                unique: false,
                persistent: true,
                hidden: false,
                clearOnHide: true,
                refreshOn: "",
                redrawOn: "",
                modalEdit: false,
                dataGridLabel: false,
                labelPosition: "top",
                description: "",
                errorLabel: "",
                tooltip: "",
                hideLabel: false,
                tabindex: "",
                disabled: false,
                autofocus: false,
                dbIndex: false,
                customDefaultValue: "",
                calculateValue: "",
                calculateServer: false,
                widget: {
                  type: "input",
                },
                attributes: {},
                validateOn: "change",
                validate: {
                  required: false,
                  custom: "",
                  customPrivate: false,
                  strictDateValidation: false,
                  multiple: false,
                  unique: false,
                  minLength: "",
                  maxLength: "",
                  pattern: "",
                },
                conditional: {
                  show: null,
                  when: null,
                  eq: "",
                },
                overlay: {
                  style: "",
                  left: "",
                  top: "",
                  width: "",
                  height: "",
                },
                allowCalculateOverride: false,
                encrypted: false,
                showCharCount: false,
                showWordCount: false,
                properties: {},
                allowMultipleMasks: false,
                addons: [],
                mask: false,
                inputType: "text",
                inputFormat: "plain",
                inputMask: "",
                displayMask: "",
                spellcheck: true,
                truncateMultipleSpaces: false,
                id: "eflbl1",
              },
              {
                label: "State",
                tableView: false,
                key: "state",
                type: "textfield",
                input: true,
                customConditional:
                  "show = _.get(instance, 'parent.manualMode', false);",
                placeholder: "",
                prefix: "",
                customClass: "",
                suffix: "",
                multiple: false,
                defaultValue: null,
                protected: false,
                unique: false,
                persistent: true,
                hidden: false,
                clearOnHide: true,
                refreshOn: "",
                redrawOn: "",
                modalEdit: false,
                dataGridLabel: false,
                labelPosition: "top",
                description: "",
                errorLabel: "",
                tooltip: "",
                hideLabel: false,
                tabindex: "",
                disabled: false,
                autofocus: false,
                dbIndex: false,
                customDefaultValue: "",
                calculateValue: "",
                calculateServer: false,
                widget: {
                  type: "input",
                },
                attributes: {},
                validateOn: "change",
                validate: {
                  required: false,
                  custom: "",
                  customPrivate: false,
                  strictDateValidation: false,
                  multiple: false,
                  unique: false,
                  minLength: "",
                  maxLength: "",
                  pattern: "",
                },
                conditional: {
                  show: null,
                  when: null,
                  eq: "",
                },
                overlay: {
                  style: "",
                  left: "",
                  top: "",
                  width: "",
                  height: "",
                },
                allowCalculateOverride: false,
                encrypted: false,
                showCharCount: false,
                showWordCount: false,
                properties: {},
                allowMultipleMasks: false,
                addons: [],
                mask: false,
                inputType: "text",
                inputFormat: "plain",
                inputMask: "",
                displayMask: "",
                spellcheck: true,
                truncateMultipleSpaces: false,
                id: "eu2w3td",
              },
              {
                label: "Country",
                tableView: false,
                key: "country",
                type: "textfield",
                input: true,
                customConditional:
                  "show = _.get(instance, 'parent.manualMode', false);",
                placeholder: "",
                prefix: "",
                customClass: "",
                suffix: "",
                multiple: false,
                defaultValue: null,
                protected: false,
                unique: false,
                persistent: true,
                hidden: false,
                clearOnHide: true,
                refreshOn: "",
                redrawOn: "",
                modalEdit: false,
                dataGridLabel: false,
                labelPosition: "top",
                description: "",
                errorLabel: "",
                tooltip: "",
                hideLabel: false,
                tabindex: "",
                disabled: false,
                autofocus: false,
                dbIndex: false,
                customDefaultValue: "",
                calculateValue: "",
                calculateServer: false,
                widget: {
                  type: "input",
                },
                attributes: {},
                validateOn: "change",
                validate: {
                  required: false,
                  custom: "",
                  customPrivate: false,
                  strictDateValidation: false,
                  multiple: false,
                  unique: false,
                  minLength: "",
                  maxLength: "",
                  pattern: "",
                },
                conditional: {
                  show: null,
                  when: null,
                  eq: "",
                },
                overlay: {
                  style: "",
                  left: "",
                  top: "",
                  width: "",
                  height: "",
                },
                allowCalculateOverride: false,
                encrypted: false,
                showCharCount: false,
                showWordCount: false,
                properties: {},
                allowMultipleMasks: false,
                addons: [],
                mask: false,
                inputType: "text",
                inputFormat: "plain",
                inputMask: "",
                displayMask: "",
                spellcheck: true,
                truncateMultipleSpaces: false,
                id: "evbbkq4",
              },
              {
                label: "Zip Code",
                tableView: false,
                key: "zip",
                type: "textfield",
                input: true,
                customConditional:
                  "show = _.get(instance, 'parent.manualMode', false);",
                placeholder: "",
                prefix: "",
                customClass: "",
                suffix: "",
                multiple: false,
                defaultValue: null,
                protected: false,
                unique: false,
                persistent: true,
                hidden: false,
                clearOnHide: true,
                refreshOn: "",
                redrawOn: "",
                modalEdit: false,
                dataGridLabel: false,
                labelPosition: "top",
                description: "",
                errorLabel: "",
                tooltip: "",
                hideLabel: false,
                tabindex: "",
                disabled: false,
                autofocus: false,
                dbIndex: false,
                customDefaultValue: "",
                calculateValue: "",
                calculateServer: false,
                widget: {
                  type: "input",
                },
                attributes: {},
                validateOn: "change",
                validate: {
                  required: false,
                  custom: "",
                  customPrivate: false,
                  strictDateValidation: false,
                  multiple: false,
                  unique: false,
                  minLength: "",
                  maxLength: "",
                  pattern: "",
                },
                conditional: {
                  show: null,
                  when: null,
                  eq: "",
                },
                overlay: {
                  style: "",
                  left: "",
                  top: "",
                  width: "",
                  height: "",
                },
                allowCalculateOverride: false,
                encrypted: false,
                showCharCount: false,
                showWordCount: false,
                properties: {},
                allowMultipleMasks: false,
                addons: [],
                mask: false,
                inputType: "text",
                inputFormat: "plain",
                inputMask: "",
                displayMask: "",
                spellcheck: true,
                truncateMultipleSpaces: false,
                id: "e9iiri",
              },
            ],
            id: "eviy2ni",
            defaultValue: {},
          },
          {
            label: "Day",
            hideInputLabels: false,
            inputsLabelPosition: "top",
            description: "",
            useLocaleSettings: false,
            tooltip: "",
            customClass: "",
            tabindex: "",
            hidden: false,
            hideLabel: false,
            autofocus: false,
            disabled: false,
            tableView: false,
            modalEdit: false,
            fields: {
              day: {
                type: "number",
                placeholder: "",
                hide: false,
                required: false,
              },
              month: {
                type: "select",
                placeholder: "",
                hide: false,
                required: false,
              },
              year: {
                type: "number",
                placeholder: "",
                hide: false,
                required: false,
              },
            },
            dayFirst: true,
            defaultValue: "00/00/0000",
            persistent: true,
            protected: false,
            dbIndex: false,
            encrypted: false,
            redrawOn: "",
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validateOn: "change",
            maxDate: "",
            minDate: "",
            unique: false,
            errorLabel: "",
            validate: {
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              required: false,
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            errors: "",
            key: "day",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "day",
            input: true,
            placeholder: "",
            prefix: "",
            suffix: "",
            multiple: false,
            refreshOn: "",
            dataGridLabel: false,
            labelPosition: "top",
            widget: null,
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            id: "eqeta8a",
          },
          {
            label: "Citizenship",
            labelPosition: "top",
            optionsLabelPosition: "right",
            description: "",
            tooltip: "",
            customClass: "",
            tabindex: "",
            inline: false,
            hidden: false,
            hideLabel: false,
            autofocus: false,
            disabled: false,
            tableView: false,
            modalEdit: false,
            dataSrc: "values",
            values: [
              {
                label: "US Citizen",
                value: "usCitizen",
                shortcut: "",
              },
              {
                label: "EU citizen",
                value: "euCitizen",
                shortcut: "",
              },
              {
                label: "Other",
                value: "other",
                shortcut: "",
              },
            ],
            dataType: "",
            valueProperty: "",
            persistent: true,
            protected: false,
            dbIndex: false,
            encrypted: false,
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validate: {
              required: false,
              onlyAvailableItems: false,
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            errorLabel: "",
            errors: "",
            key: "citizenship",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "radio",
            data: {
              url: "",
            },
            template: "<span>{{ item.label }}</span>",
            redrawOn: "",
            input: true,
            placeholder: "",
            prefix: "",
            suffix: "",
            multiple: false,
            unique: false,
            refreshOn: "",
            dataGridLabel: false,
            widget: null,
            validateOn: "change",
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            authenticate: false,
            ignoreCache: false,
            inputType: "radio",
            fieldSet: false,
            id: "ee7acxf",
            defaultValue: "",
          },
          {
            label: "Marital Status",
            labelPosition: "top",
            widget: "choicesjs",
            placeholder: "",
            description: "",
            tooltip: "",
            customClass: "",
            tabindex: "",
            hidden: false,
            hideLabel: false,
            uniqueOptions: false,
            autofocus: false,
            disabled: false,
            tableView: true,
            modalEdit: false,
            multiple: false,
            dataSrc: "values",
            data: {
              values: [
                {
                  label: "Married",
                  value: "married",
                },
                {
                  label: "Single",
                  value: "single",
                },
                {
                  label: "Divorced",
                  value: "divorced",
                },
                {
                  label: "Widowed",
                  value: "widowed",
                },
                {
                  label: "Separated",
                  value: "separated",
                },
              ],
              resource: "",
              url: "",
              json: "",
              custom: "",
            },
            dataType: "",
            idPath: "id",
            valueProperty: "",
            template: "<span>{{ item.label }}</span>",
            refreshOn: "",
            refreshOnBlur: "",
            clearOnRefresh: false,
            searchEnabled: true,
            selectThreshold: 0.3,
            readOnlyValue: false,
            customOptions: {},
            useExactSearch: false,
            persistent: true,
            protected: false,
            dbIndex: false,
            encrypted: false,
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validateOn: "change",
            validate: {
              required: false,
              onlyAvailableItems: false,
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            unique: false,
            errorLabel: "",
            errors: "",
            key: "maritalStatus",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "select",
            indexeddb: {
              filter: {},
            },
            selectFields: "",
            searchField: "",
            searchDebounce: 0.3,
            minSearch: 0,
            filter: "",
            limit: 100,
            redrawOn: "",
            input: true,
            prefix: "",
            suffix: "",
            dataGridLabel: false,
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            authenticate: false,
            ignoreCache: false,
            lazyLoad: true,
            fuseOptions: {
              include: "score",
              threshold: 0.3,
            },
            id: "ekr2zja",
            defaultValue: "",
          },
          {
            label: "Occupation",
            labelPosition: "top",
            placeholder: "",
            description: "",
            tooltip: "",
            prefix: "",
            suffix: "",
            widget: {
              type: "input",
            },
            inputMask: "",
            displayMask: "",
            allowMultipleMasks: false,
            customClass: "",
            tabindex: "",
            autocomplete: "",
            hidden: false,
            hideLabel: false,
            showWordCount: false,
            showCharCount: false,
            mask: false,
            autofocus: false,
            spellcheck: true,
            disabled: false,
            tableView: true,
            modalEdit: false,
            multiple: false,
            persistent: true,
            inputFormat: "plain",
            protected: false,
            dbIndex: false,
            case: "",
            truncateMultipleSpaces: false,
            encrypted: false,
            redrawOn: "",
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validateOn: "change",
            validate: {
              required: false,
              pattern: "",
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              minLength: "",
              maxLength: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            unique: false,
            errorLabel: "",
            errors: "",
            key: "occupation",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "textfield",
            input: true,
            refreshOn: "",
            dataGridLabel: false,
            addons: [],
            inputType: "text",
            id: "ea9be1",
            defaultValue: "",
          },
          {
            label: "How can we improve our services?",
            labelPosition: "top",
            placeholder: "",
            description: "",
            tooltip: "",
            prefix: "",
            suffix: "",
            widget: {
              type: "input",
            },
            displayMask: "",
            editor: "",
            autoExpand: false,
            customClass: "",
            tabindex: "",
            autocomplete: "",
            hidden: false,
            hideLabel: false,
            showWordCount: false,
            showCharCount: false,
            autofocus: false,
            spellcheck: true,
            disabled: false,
            tableView: true,
            modalEdit: false,
            multiple: false,
            persistent: true,
            inputFormat: "html",
            protected: false,
            dbIndex: false,
            case: "",
            truncateMultipleSpaces: false,
            encrypted: false,
            redrawOn: "",
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validateOn: "change",
            validate: {
              required: false,
              pattern: "",
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              minLength: "",
              maxLength: "",
              minWords: "",
              maxWords: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            unique: false,
            errorLabel: "",
            errors: "",
            key: "howCanWeImproveOurServices",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "textarea",
            rows: 3,
            wysiwyg: false,
            input: true,
            refreshOn: "",
            dataGridLabel: false,
            allowMultipleMasks: false,
            addons: [],
            mask: false,
            inputType: "text",
            inputMask: "",
            fixedSize: true,
            id: "e9nomnc",
            defaultValue: "",
          },
          {
            label: "Survey",
            labelPosition: "top",
            description: "",
            tooltip: "",
            customClass: "",
            tabindex: "",
            hidden: false,
            hideLabel: false,
            autofocus: false,
            disabled: false,
            tableView: false,
            modalEdit: false,
            questions: [
              {
                label: "How satisfied  are you with our service you received ?",
                value: "howSatisfiedAreYouWithOurServiceYouReceived",
                tooltip: "",
              },
            ],
            values: [
              {
                label: "Very Satisfied",
                value: "verySatisfied",
                tooltip: "",
              },
              {
                label: "Good",
                value: "good",
                tooltip: "",
              },
              {
                label: "Normal",
                value: "normal",
                tooltip: "",
              },
              {
                label: "Dissatisfied",
                value: "dissatisfied",
                tooltip: "",
              },
            ],
            persistent: true,
            protected: false,
            dbIndex: false,
            encrypted: false,
            redrawOn: "",
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validate: {
              required: false,
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            unique: false,
            errorLabel: "",
            errors: "",
            key: "survey",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "survey",
            input: true,
            placeholder: "",
            prefix: "",
            suffix: "",
            multiple: false,
            refreshOn: "",
            dataGridLabel: false,
            widget: null,
            validateOn: "change",
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            id: "e0602pq",
            defaultValue: {},
          },
          {
            label: "Do you want to add joint owner to the bank account?",
            labelPosition: "top",
            optionsLabelPosition: "right",
            description: "",
            tooltip: "",
            customClass: "",
            tabindex: "",
            inline: false,
            hidden: false,
            hideLabel: false,
            autofocus: false,
            disabled: false,
            tableView: false,
            modalEdit: false,
            dataSrc: "values",
            values: [
              {
                label: "Yes",
                value: "yes",
                shortcut: "",
              },
              {
                label: "No",
                value: "no",
                shortcut: "",
              },
            ],
            dataType: "",
            valueProperty: "",
            persistent: true,
            protected: false,
            dbIndex: false,
            encrypted: false,
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validate: {
              required: false,
              onlyAvailableItems: false,
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            errorLabel: "",
            errors: "",
            key: "doYouWantToAddJointOwnerToTheBankAccount",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "radio",
            data: {
              url: "",
            },
            template: "<span>{{ item.label }}</span>",
            redrawOn: "",
            input: true,
            placeholder: "",
            prefix: "",
            suffix: "",
            multiple: false,
            unique: false,
            refreshOn: "",
            dataGridLabel: false,
            widget: null,
            validateOn: "change",
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            authenticate: false,
            ignoreCache: false,
            inputType: "radio",
            fieldSet: false,
            id: "eqe33lw",
            defaultValue: "",
          },
          {
            label: "I agree to terms & conditions.",
            description: "",
            tooltip: "",
            shortcut: "",
            inputType: "checkbox",
            customClass: "",
            tabindex: "",
            hidden: false,
            hideLabel: false,
            autofocus: false,
            disabled: false,
            tableView: false,
            modalEdit: false,
            persistent: true,
            protected: false,
            dbIndex: false,
            encrypted: false,
            redrawOn: "",
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validate: {
              required: false,
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            errorLabel: "",
            errors: "",
            key: "iAgreeToTermsConditions",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "checkbox",
            name: "",
            value: "",
            input: true,
            placeholder: "",
            prefix: "",
            suffix: "",
            multiple: false,
            unique: false,
            refreshOn: "",
            dataGridLabel: true,
            labelPosition: "right",
            widget: null,
            validateOn: "change",
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            id: "eh6rqow",
            defaultValue: false,
          },
          {
            label: "Primary Owner Signature",
            footer: "Sign above",
            labelPosition: "top",
            width: "100%",
            height: "150px",
            backgroundColor: "rgb(245,245,235)",
            penColor: "black",
            description: "",
            tooltip: "",
            customClass: "",
            tabindex: "",
            hidden: false,
            hideLabel: false,
            disabled: false,
            tableView: false,
            modalEdit: false,
            persistent: true,
            protected: false,
            encrypted: false,
            redrawOn: "",
            clearOnHide: true,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            allowCalculateOverride: false,
            validate: {
              required: false,
              customMessage: "",
              custom: "",
              customPrivate: false,
              json: "",
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            errorLabel: "",
            errors: "",
            key: "primaryOwnerSignature",
            tags: [],
            properties: {},
            conditional: {
              show: null,
              when: null,
              eq: "",
              json: "",
            },
            customConditional: "",
            logic: [],
            attributes: {},
            overlay: {
              style: "",
              page: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            type: "signature",
            input: true,
            placeholder: "",
            prefix: "",
            suffix: "",
            multiple: false,
            defaultValue: null,
            unique: false,
            refreshOn: "",
            dataGridLabel: false,
            autofocus: false,
            dbIndex: false,
            widget: {
              type: "input",
            },
            validateOn: "change",
            showCharCount: false,
            showWordCount: false,
            allowMultipleMasks: false,
            addons: [],
            minWidth: "0.5",
            maxWidth: "2.5",
            keepOverlayRatio: true,
            id: "e69se8t",
          },
          {
            type: "button",
            label: "Submit",
            key: "submit",
            size: "md",
            block: false,
            action: "submit",
            disableOnInvalid: true,
            theme: "primary",
            input: true,
            placeholder: "",
            prefix: "",
            customClass: "",
            suffix: "",
            multiple: false,
            defaultValue: null,
            protected: false,
            unique: false,
            persistent: false,
            hidden: false,
            clearOnHide: true,
            refreshOn: "",
            redrawOn: "",
            tableView: false,
            modalEdit: false,
            dataGridLabel: true,
            labelPosition: "top",
            description: "",
            errorLabel: "",
            tooltip: "",
            hideLabel: false,
            tabindex: "",
            disabled: false,
            autofocus: false,
            dbIndex: false,
            customDefaultValue: "",
            calculateValue: "",
            calculateServer: false,
            widget: {
              type: "input",
            },
            attributes: {},
            validateOn: "change",
            validate: {
              required: false,
              custom: "",
              customPrivate: false,
              strictDateValidation: false,
              multiple: false,
              unique: false,
            },
            conditional: {
              show: null,
              when: null,
              eq: "",
            },
            overlay: {
              style: "",
              left: "",
              top: "",
              width: "",
              height: "",
            },
            allowCalculateOverride: false,
            encrypted: false,
            showCharCount: false,
            showWordCount: false,
            properties: {},
            allowMultipleMasks: false,
            addons: [],
            leftIcon: "",
            rightIcon: "",
            id: "e313w7k",
          },
        ],
      }}
      onChange={(schema) => console.log(schema)}
    />
  );
};

export default RenderForm;
